export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const SET_REGISTER_CREDENTIALS = 'SET_REGISTER_CREDENTIALS'