export const REQUEST_USER_DETAILS = 'REQUEST_USER_DETAILS'
export const REQUEST_USER_DETAILS_SUCCESS = 'REQUEST_USER_DETAILS_SUCCESS'
export const REQUEST_USER_DETAILS_FAILED = 'REQUEST_USER_DETAILS_FAILED'